apiVersion: apps/v1
kind: Deployment
metadata:
  name: brokencrystals
  labels:
    app: brokencrystals
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  brokencrystals
  template:
    metadata:
      labels:
        app: brokencrystals
    spec:
      containers:
      - name: brokencrystals
        image: dubcygoat/brokencrystals:v1
        ports:
        - containerPort: 3000  # Application's primary port
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_DB
          value: "db"  # Name of the database service
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: DATABASE_PORT
          value: "5432"
        livenessProbe:
          httpGet:
            path: /health  
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ready  
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: brokencrystals
spec:
  selector:
    app: brokencrystals
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
